services:
  otomoto-app:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '1g' # Add this line
    container_name: otomoto-app
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - FIREFOX_BINARY=${FIREFOX_BINARY}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    networks:
      - otomoto_network

  postgres:
    image: postgres:latest
    container_name: postgres_otomoto
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - otomoto_network

volumes:
  postgres_data:

networks:
  otomoto_network:
    name: otomoto_network
