services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    environment:
      - CHROME_BIN=/usr/bin/google-chrome
      - CHROME_PATH=/usr/bin/google-chrome
      - POSTGRES_URI=${POSTGRES_URI}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    networks:
      - otomoto_network

  postgres:
    image: postgres:latest
    container_name: postgres_otomoto
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - otomoto_network

volumes:
  postgres_data:

networks:
  otomoto_network:
