export const filters = [
    {
        brand: 'ford',
        model: 'focus',
        fromYear: '2011',
        city: 'krakow',
        lat: '50.07567',
        lon: '19.93084',
        distance: '15',
        fuelType: 'petrol',
        gearbox: 'manual',
        engine_capacity_from: '1500',
        engine_capacity_to: '1650',
        price_from: '15000',
        price_to: '35000',
        sortBy: 'created_at_first',
    },
    {
        brand: 'renault',
        model: 'megane',
        fromYear: '2011',
        city: 'krakow',
        lat: '50.07567',
        lon: '19.93084',
        distance: '15',
        fuelType: 'petrol',
        gearbox: 'manual',
        engine_capacity_from: '1450',
        engine_capacity_to: '1650',
        price_from: '15000',
        price_to: '35000',
        sortBy: 'created_at_first',
    },
    {
        brand: 'dacia',
        model: 'duster',
        fromYear: '2014',
        city: 'krakow',
        lat: '50.07567',
        lon: '19.93084',
        distance: '15',
        fuelType: 'petrol',
        gearbox: 'manual',
        engine_capacity_from: '1450',
        engine_capacity_to: '1650',
        price_from: '15000',
        price_to: '35000',
        sortBy: 'created_at_first',
    },
    {
        brand: 'ford',
        model: 'focus',
        fromYear: '2011',
        city: 'katowice',
        lat: '50.26288',
        lon: '19.02276',
        distance: '10',
        fuelType: 'petrol',
        gearbox: 'manual',
        engine_capacity_from: '1500',
        engine_capacity_to: '1650',
        price_from: '15000',
        price_to: '35000',
        sortBy: 'created_at_first',
    },
    {
        brand: 'renault',
        model: 'megane',
        fromYear: '2011',
        city: 'katowice',
        lat: '50.26288',
        lon: '19.02276',
        distance: '10',
        fuelType: 'petrol',
        gearbox: 'manual',
        engine_capacity_from: '1450',
        engine_capacity_to: '1650',
        price_from: '15000',
        price_to: '35000',
        sortBy: 'created_at_first',
    },
    {
        brand: 'dacia',
        model: 'duster',
        fromYear: '2014',
        city: 'katowice',
        lat: '50.26288',
        lon: '19.02276',
        distance: '10',
        fuelType: 'petrol',
        gearbox: 'manual',
        engine_capacity_from: '1450',
        engine_capacity_to: '1650',
        price_from: '15000',
        price_to: '35000',
        sortBy: 'created_at_first',
    }
]